### ISSUE TITLE
ESPHome integration

### ISSUE THREAD

**Issue by peepshow-21** [joBr99/nspanel-lovelance-ui#1]
Hi,

I did the ns-flash tool for loading custom HMI's to the Tasmota based NSPanels, which you found helpful (I think) to upload your HMI.

I have also done a generic HMI for the NSPanel which you can communicate with over JSON (over MQTT on the Tasmota version).

It, like yours, uses a protocol very similar to that used by the stock HMI. I do not really know much about ESPHome but I would imagine it's very easy to get it to work with ESPHome too. If you are interested, you can have a look here. Might only take you a short time to get ESPHome working with that too. If that was on interest to you;

https://community.openhab.org/t/nxpanel-replacement-firmware-for-sonoff-nspanel/132869

Thanks

**Comment by joBr99** [comment]
Hey, 
I'm indeed also more a tasmota user, so your ns-flash stuff is really helpful. 
I didn't really do anything on the esphome side after switching back to tasmota and ns-flash.

My goal with this HMI was/is to get as close as possibe to an look and feel that you have with lovelance UI from homeassistant.
And I didn't brother to implement something in json, because I think that this is not really practical for the nextion instruction set and a bit over-engineered. Instead a used messages with comma seperated values.

If you want to have a chat, hit me up on the unoffical nextion discord, would love to hear how far implemented the json stuff.

**Comment by joBr99** [comment]
I removed everything releated to esphome, my esphome component was a proof of concept. If somebody wants to continue my esphome component I'm open for this. Extending my existing esphome component code to be useable like my tasmota berry driver isn't much work, but I'm going to use tasmota on my devices.
